import { createContext, useContext, useState, useEffect } from "react"

const LanguageContext = createContext()

// Translation keys and their values
const translations = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.academies": "Academies", 
    "nav.matches": "Matches",
    "nav.jobs": "Job Opportunities",
    "nav.login": "Login",
    "nav.signup": "Sign Up",
    "nav.logout": "Logout",
    
    // Auth
    "auth.login": "Login",
    "auth.signup": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.name": "Name",
    "auth.phone": "Phone",
    "auth.loginButton": "Login",
    "auth.signupButton": "Sign Up",
    "auth.logoutButton": "Logout",
    "auth.invalidCredentials": "Invalid credentials",
    "auth.emailExists": "Email already exists",
    "auth.loginFailed": "Login failed",
    "auth.registrationFailed": "Registration failed",
    "auth.dontHaveAccount": "Don't have an account?",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.fullName": "Full name",
    "auth.phoneOptional": "Phone (optional)",
    "auth.passwordMin": "Password (min 6 chars)",
    "auth.loggingIn": "Logging in...",
    "auth.signingUp": "Signing up...",
    
    // Admin
    "admin.dashboard": "Dashboard",
    "admin.users": "Users",
    "admin.academies": "Academies",
    "admin.matches": "Matches",
    "admin.requests": "Player Requests",
    "admin.createAcademy": "Create Academy Account",
    "admin.panel": "Admin Panel",
    "admin.usersManagement": "Users Management",
    "admin.administrators": "Administrators",
    "admin.academyAccounts": "Academy Accounts",
    "admin.regularUsers": "Users",
    "admin.addUser": "Add User",
    "admin.delete": "Delete",
    "admin.noAdmins": "No administrators found",
    "admin.noAcademies": "No academy accounts found",
    "admin.noUsers": "No regular users found",
    "admin.welcomeBack": "Welcome back",
    "admin.platformOverview": "Here's your platform overview",
    "admin.totalUsers": "Total Users",
    "admin.totalAcademies": "Academies",
    "admin.totalMatches": "Matches",
    "admin.pendingRequests": "Pending Requests",
    "admin.recentRequests": "Recent Requests",
    "admin.viewAll": "View all",
    "admin.quickActions": "Quick Actions",
    "admin.manageAcademies": "Manage Academies",
    "admin.manageAcademiesDesc": "View and manage all football academies",
    "admin.manageMatches": "Manage Matches",
    "admin.manageMatchesDesc": "Oversee scheduled matches and events",
    "admin.manageRequests": "Manage Requests",
    "admin.manageRequestsDesc": "Handle academy join requests",
    "admin.manageUsers": "Manage Users",
    "admin.manageUsersDesc": "View and manage user accounts",
    "admin.platformStatus": "Platform Status",
    "admin.allSystemsOperational": "All systems operational",
    "admin.online": "Online",
    "admin.noRequestsYet": "No requests yet",
    
    // Academy
    "academy.dashboard": "Dashboard",
    "academy.players": "Players",
    "academy.matches": "Matches",
    "academy.requests": "Requests",
    "academy.analysis": "Analysis",
    "academy.jobs": "Jobs",
    "academy.panel": "Academy Panel",
    "academy.welcomeBack": "Welcome back",
    "academy.overview": "Here's your academy overview",
    "academy.totalPlayers": "Total Players",
    "academy.activeMatches": "Active Matches",
    "academy.pendingRequests": "Pending Requests",
    "academy.jobPostings": "Job Postings",
    "academy.recentActivity": "Recent Activity",
    "academy.viewAll": "View all",
    "academy.quickActions": "Quick Actions",
    "academy.managePlayers": "Manage Players",
    "academy.managePlayersDesc": "View and manage academy players",
    "academy.scheduleMatch": "Schedule Match",
    "academy.scheduleMatchDesc": "Create new match requests",
    "academy.viewRequests": "View Requests",
    "academy.viewRequestsDesc": "Handle player join requests",
    "academy.postJob": "Post Job",
    "academy.postJobDesc": "Create new job opportunities",
    "academy.academyStatus": "Academy Status",
    "academy.allSystemsOperational": "All systems operational",
    "academy.online": "Online",
    "academy.noActivityYet": "No activity yet",
    "academy.avgAge": "Avg Age",
    "academy.positionBreakdown": "Position Breakdown",
    "academy.addPlayer": "Add Player",
    "academy.refresh": "Refresh",
    "academy.searchPlayers": "Search players...",
    "academy.filterAllPositions": "Filter: All positions",
    "academy.clearFilter": "Clear filter",
    "academy.noDataYet": "No data yet",
    "academy.noPlayersFound": "No players found",
    "academy.addNewPlayer": "Add New Player",
    "academy.fullName": "Full name",
    "academy.age": "Age",
    "academy.position": "Position",
    "academy.selectPosition": "Select position (optional)",
    "academy.forward": "Forward",
    "academy.midfielder": "Midfielder",
    "academy.defender": "Defender",
    "academy.goalkeeper": "Goalkeeper",
    "academy.other": "Other",
    "academy.uploadAvatar": "Upload avatar (optional)",
    "academy.saving": "Saving...",
    "academy.savePlayer": "Save Player",
    "academy.deletePlayer": "Delete player",
    "academy.deletePlayerConfirm": "Delete player? This action cannot be undone.",
    "academy.couldNotRemovePlayer": "Could not remove player",
    "academy.pleaseProvideName": "Please provide the player's name",
    "academy.failedToAddPlayer": "Failed to add player",
    
    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.retry": "Retry",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.confirm": "Confirm",
    "common.yes": "Yes",
    "common.no": "No",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.clear": "Clear",
    "common.submit": "Submit",
    "common.close": "Close",
    "common.open": "Open",
    "common.view": "View",
    "common.details": "Details",
    "common.status": "Status",
    "common.date": "Date",
    "common.time": "Time",
    "common.location": "Location",
    "common.description": "Description",
    "common.name": "Name",
    "common.email": "Email",
    "common.phone": "Phone",
    "common.role": "Role",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.pending": "Pending",
    "common.approved": "Approved",
    "common.rejected": "Rejected",
    "common.failed": "Failed",
    "common.success": "Success",
    "common.warning": "Warning",
    "common.info": "Info",
    "common.notFound": "Not Found",
    "common.accessDenied": "Access Denied",
    "common.unauthorized": "Unauthorized",
    "common.forbidden": "Forbidden",
    "common.serverError": "Server Error",
    "common.networkError": "Network Error",
    "common.tryAgain": "Try Again",
    "common.refresh": "Refresh",
    "common.somethingWentWrong": "Something went wrong",
    "common.pleaseRefresh": "Please refresh the page. If the issue persists, try again later.",
    "common.failedToLoad": "Failed to load",
    "common.confirmDelete": "Are you sure you want to delete this",
    "common.user": "user",
    "common.failedToDelete": "Failed to delete",
    
    // Public Pages
    "public.welcome": "Welcome to DWARLY",
    "public.tagline": "Connecting Egyptian football families with the best academies",
    "public.getStarted": "Get Started",
    "public.learnMore": "Learn More",
    "public.features": "Features",
    "public.findAcademies": "Find Academies",
    "public.findAcademiesDesc": "Discover top football academies across Egypt",
    "public.scheduleMatches": "Schedule Matches",
    "public.scheduleMatchesDesc": "Organize matches between academies",
    "public.jobOpportunities": "Job Opportunities",
    "public.jobOpportunitiesDesc": "Find coaching and training positions",
    "public.playerManagement": "Player Management",
    "public.playerManagementDesc": "Track player progress and development",
    "public.aboutUs": "About Us",
    "public.aboutUsDesc": "DWARLY is dedicated to supporting Egyptian football development",
    "public.contact": "Contact",
    "public.followUs": "Follow Us",
    "public.madeForEgyptian": "Made for Egyptian football families. ⚽🇪🇬",
    
    // Academies Page
    "academies.title": "Academies",
    "academies.search": "Search",
    "academies.add": "Add",
    "academies.verified": "Verified",
    "academies.rating": "Rating",
    "academies.location": "Location",
    "academies.phone": "Phone",
    "academies.email": "Email",
    "academies.subscription": "Subscription",
    "academies.girls": "Girls",
    "academies.boys": "Boys",
    "academies.training": "Training",
    "academies.join": "Join",
    "academies.joining": "Joining...",
    "academies.approved": "Approved",
    "academies.rejected": "Rejected (Can reapply)",
    "academies.pending": "Pending",
    "academies.close": "Close",
    "academies.refresh": "Refresh",
    "academies.delete": "Delete",
    "academies.addAcademy": "Add Academy",
    "academies.pickLocation": "Pick Location on Map",
    "academies.initialRating": "Initial Rating",
    "academies.groups": "Groups",
    "academies.subscriptionPrice": "Subscription Price (EGP)",
    "academies.trainingTimes": "Training Times",
    "academies.day": "Day",
    "academies.time": "Time",
    "academies.cancel": "Cancel",
    "academies.save": "Save",
    "academies.joinRequestSent": "Join request sent successfully!",
    "academies.joinRequestFailed": "Failed to send join request.",
    
    // Job Opportunities Page
    "jobs.title": "Coaching Job Opportunities",
    "jobs.subtitle": "Find your next coaching position at top football academies across Egypt. Apply with your CV and start your coaching journey.",
    "jobs.search": "Search jobs, academies, or locations...",
    "jobs.filter": "Filter",
    "jobs.allTypes": "All Types",
    "jobs.fullTime": "Full-time",
    "jobs.partTime": "Part-time",
    "jobs.contract": "Contract",
    "jobs.volunteer": "Volunteer",
    "jobs.availableJobs": "Available Jobs",
    "jobs.participatingAcademies": "Participating Academies",
    "jobs.yourApplications": "Your Applications",
    "jobs.noJobsFound": "No jobs found",
    "jobs.tryAdjusting": "Try adjusting your search or filter criteria",
    "jobs.checkBackLater": "Check back later for new opportunities",
    "jobs.loading": "Loading job opportunities...",
    "jobs.applyNow": "Apply Now",
    "jobs.youHaveApplied": "You have applied for this position",
    "jobs.rejectedCanReapply": "Rejected (Can reapply)",
    "jobs.deadlinePassed": "Application deadline has passed",
    "jobs.deadlinePassedTitle": "Deadline Passed",
    "jobs.applyForPosition": "Apply for Position",
    "jobs.coverLetter": "Cover Letter",
    "jobs.coverLetterPlaceholder": "Tell us why you're the perfect fit for this position...",
    "jobs.coachingExperience": "Coaching Experience",
    "jobs.experiencePlaceholder": "Describe your coaching experience and achievements...",
    "jobs.qualifications": "Qualifications & Certifications",
    "jobs.qualificationsPlaceholder": "List your coaching licenses, certifications, and relevant qualifications...",
    "jobs.uploadCV": "Upload CV",
    "jobs.clickToUpload": "Click to upload your CV",
    "jobs.cvFormats": "PDF, DOC, or DOCX (max 5MB)",
    "jobs.cvUploaded": "CV uploaded successfully",
    "jobs.submitApplication": "Submit Application",
    "jobs.submitting": "Submitting...",
    "jobs.pleaseWriteCoverLetter": "Please write a cover letter",
    "jobs.pleaseUploadCV": "Please upload your CV",
    "jobs.cvFileSizeLimit": "CV file size must be less than 5MB",
    "jobs.applicationSubmitted": "Application submitted successfully!",
    "jobs.failedToSubmit": "Failed to submit application",
    "jobs.requirements": "Requirements:",
    "jobs.posted": "Posted",
    "jobs.applyBy": "Apply by",
    "jobs.at": "at",
    "jobs.rating": "Rating",
    "jobs.subscription": "Subscription",
    "jobs.groups": "Groups",
    "jobs.girls": "Girls",
    "jobs.boys": "Boys",
    "jobs.contact": "Contact",
    "jobs.location": "Location",
    "jobs.trainingTimes": "Training Times",
    "jobs.uploadAvatarsFilter": "upload avatars, filter and analyze.",
    "jobs.defender": "Defender",
    "jobs.midfielder": "Midfielder",
    "jobs.forward": "Forward",
    "jobs.age": "Age",
    
    // Academy Match Requests
    "academyMatch.title": "Academy Match Requests",
    "academyMatch.description": "Manage your match requests and find opponents",
    "academyMatch.newRequest": "New Request",
    "academyMatch.available": "Available",
    "academyMatch.confirmed": "Confirmed",
    "academyMatch.finished": "Finished",
    "academyMatch.matchDateTime": "Match Date & Time",
    "academyMatch.ageGroup": "Age Group",
    "academyMatch.contactDuration": "Contact & Duration",
    "academyMatch.finishMatch": "Finish Match",
    "academyMatch.hour": "hour",
    
    // Academy Requests
    "academyRequests.title": "Join Requests",
    "academyRequests.noRequests": "No join requests yet.",
    
    // Academy Analytics
    "academyAnalytics.title": "Academy Analytics",
    "academyAnalytics.description": "Live KPIs on players, matches, requests, and finance.",
    "academyAnalytics.refresh": "Refresh",
    "academyAnalytics.players": "Players",
    "academyAnalytics.matches": "Matches",
    "academyAnalytics.income": "Income",
    "academyAnalytics.balance": "Balance",
    "academyAnalytics.playersByPosition": "Players by Position",
    "academyAnalytics.playersByAge": "Players by Age",
    "academyAnalytics.matchesRequests": "Matches & Requests",
    "academyAnalytics.matchesStatus": "Matches Status",
    "academyAnalytics.playerRequests": "Player Requests",
    "academyAnalytics.noRequestsYet": "No requests yet.",
    "academyAnalytics.total": "Total",
    
    // Finance
    "finance.title": "Finance",
    "finance.income": "Income",
    "finance.amount": "Amount (EGP)",
    "finance.category": "Category",
    "finance.date": "mm/dd/yyyy",
    "finance.note": "Note",
    "finance.addEntry": "Add Entry",
    "finance.incomeType": "income",
    
    // Admin
    "admin.addAcademy": "Add Academy",
    "admin.createAcademyAccount": "Create Academy Account",
    "admin.selectAcademy": "Select Academy",
    "admin.chooseAcademy": "Choose an academy...",
    "admin.email": "Email",
    "admin.password": "Password",
    "admin.createAccount": "Create Account",
    "admin.friendlyMatches": "Friendly Matches",
    "admin.playerRequests": "Player Requests",
    "admin.noPlayerRequests": "No player requests found",
    
    // Language
    "lang.english": "English",
    "lang.arabic": "العربية",
    "lang.switchTo": "Switch to",
    
    // Home Page
    "home.verified": "Verified",
    "home.verifiedDesc": "AI-powered verification system",
    "home.rated": "Rated",
    "home.ratedDesc": "Community-driven ratings",
    "home.connected": "Connected",
    "home.connectedDesc": "Seamless matchmaking",
    "home.verifiedProfiles": "Verified Profiles",
    "home.verifiedProfilesDesc": "All academies are verified and rated by our community",
    "home.performanceTracking": "Performance Tracking",
    "home.performanceTrackingDesc": "Monitor academy performance and player development",
    "home.communityRatings": "Community Ratings",
    "home.communityRatingsDesc": "Real reviews and ratings from players and parents",
    "home.elevatingEgyptian": "Elevating Egyptian Football Talent",
    
    // Matches Page
    "matches.title": "Friendly Matches",
    "matches.search": "Search by date, status, or U-group...",
    "matches.matched": "Matched",
    "matches.requested": "Requested",
    "matches.accepted": "Accepted",
    "matches.scheduled": "Scheduled",
    "matches.contact": "Contact:",
    "matches.acceptAndShow": "Accept & Show Contacts",
    "matches.requestMatch": "Request Friendly Match",
    "matches.ageGroup": "Age Group",
    "matches.date": "Date",
    "matches.time": "Time",
    "matches.homeAway": "Home / Away",
    "matches.home": "HOME",
    "matches.away": "AWAY",
    "matches.location": "Location",
    "matches.publishing": "Publishing...",
    "matches.publish": "Publish",
    "matches.onlyAcademyAccounts": "Only academy accounts can publish match requests. Please contact admin to approve your academy access.",
    "matches.chooseDateTime": "Please choose date and time",
    "matches.pickLocation": "Please pick a location on the map",
    "matches.failedToPublish": "Failed to publish",
    "matches.failedToAccept": "Failed to accept",
    
    // Admin Academies
    "adminAcademies.title": "Admin • Academies",
    "adminAcademies.addAcademy": "Add Academy",
    "adminAcademies.retry": "Retry",
    "adminAcademies.edit": "Edit",
    "adminAcademies.delete": "Delete",
    "adminAcademies.prev": "Prev",
    "adminAcademies.next": "Next",
    "adminAcademies.page": "Page",
    "adminAcademies.of": "of",
    "adminAcademies.addAcademyModal": "Add Academy",
    "adminAcademies.editAcademyModal": "Edit Academy",
    "adminAcademies.nameEnglish": "Name (English)*",
    "adminAcademies.nameArabic": "Name (Arabic)",
    "adminAcademies.academyName": "Academy Name",
    "adminAcademies.academyNameAr": "اسم الأكاديمية",
    "adminAcademies.phone": "Phone",
    "adminAcademies.phoneNumber": "Phone Number",
    "adminAcademies.contactEmail": "Contact Email",
    "adminAcademies.description": "Description",
    "adminAcademies.academyDescription": "Academy Description",
    "adminAcademies.locationDescription": "Location Description",
    "adminAcademies.location": "Location",
    "adminAcademies.rating": "Rating:",
    "adminAcademies.availableAges": "Available Ages",
    "adminAcademies.verified": "Verified",
    "adminAcademies.girls": "Girls",
    "adminAcademies.boys": "Boys",
    "adminAcademies.subscriptionPrice": "Subscription price (EGP)",
    "adminAcademies.trainingTimes": "Training times",
    "adminAcademies.addTime": "Add time",
    "adminAcademies.day": "Day",
    "adminAcademies.time": "Time",
    "adminAcademies.logoImage": "Logo / Image",
    "adminAcademies.preview": "Preview",
    "adminAcademies.currentLogo": "Current logo",
    "adminAcademies.selected": "Selected:",
    "adminAcademies.cancel": "Cancel",
    "adminAcademies.creating": "Creating...",
    "adminAcademies.create": "Create",
    "adminAcademies.saving": "Saving...",
    "adminAcademies.save": "Save",
    "adminAcademies.nameRequired": "Name is required to create an academy.",
    "adminAcademies.failedToCreate": "Failed to create academy.",
    "adminAcademies.failedToUpdate": "Failed to update academy.",
    "adminAcademies.confirmDelete": "Are you sure you want to delete this academy?",
    "adminAcademies.failedToDelete": "Failed to delete academy.",
    "adminAcademies.failedToLoad": "Failed to load academies. Please try again.",
    
    // Academies Page
    "academies.delete": "Delete",
    "academies.verified": "Verified",
    "academies.rating": "Rating",
    "academies.subscription": "Subscription",
    "academies.training": "Training:",
    "academies.more": "more…",
    "academies.join": "Join",
    "academies.joining": "Joining...",
    "academies.approved": "Approved",
    "academies.rejected": "Rejected (Can reapply)",
    "academies.pending": "Pending",
    "academies.close": "Close",
    "academies.refreshStatus": "Refresh status",
    "academies.contact": "Contact",
    "academies.location": "Location",
    "academies.trainingTimes": "Training Times",
    "academies.addAcademyModal": "Add Academy",
    "academies.pickLocation": "Pick Location on Map",
    "academies.initialRating": "Initial Rating",
    "academies.groups": "Groups",
    "academies.subscriptionPrice": "Subscription Price (EGP)",
    "academies.day": "Day",
    "academies.time": "Time",
    "academies.cancel": "Cancel",
    "academies.save": "Save",
    "academies.joinRequestSent": "Join request sent successfully!",
    "academies.joinRequestFailed": "Failed to send join request.",
    "academies.deleteConfirm": "Delete this academy?",
    
    // Academy Dashboard
    "academy.configurationRequired": "Configuration Required",
    "academy.academyInfoMissing": "Academy information is missing. Please contact an administrator to link your account to an academy.",
    "academy.contactAdminToResolve": "To resolve this issue, please contact an administrator to properly link your academy account to an academy.",
    "academy.totalRequests": "Total Requests",
  },
  ar: {
    // Navigation
    "nav.home": "الرئيسية",
    "nav.academies": "الأكاديميات",
    "nav.matches": "المباريات",
    "nav.jobs": "فرص العمل",
    "nav.login": "تسجيل الدخول",
    "nav.signup": "إنشاء حساب",
    "nav.logout": "تسجيل الخروج",
    
    // Auth
    "auth.login": "تسجيل الدخول",
    "auth.signup": "إنشاء حساب",
    "auth.email": "البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.name": "الاسم",
    "auth.phone": "رقم الهاتف",
    "auth.loginButton": "دخول",
    "auth.signupButton": "إنشاء حساب",
    "auth.logoutButton": "خروج",
    "auth.invalidCredentials": "بيانات الدخول غير صحيحة",
    "auth.emailExists": "البريد الإلكتروني موجود بالفعل",
    "auth.loginFailed": "فشل تسجيل الدخول",
    "auth.registrationFailed": "فشل إنشاء الحساب",
    "auth.dontHaveAccount": "ليس لديك حساب؟",
    "auth.alreadyHaveAccount": "لديك حساب بالفعل؟",
    "auth.fullName": "الاسم الكامل",
    "auth.phoneOptional": "رقم الهاتف (اختياري)",
    "auth.passwordMin": "كلمة المرور (6 أحرف على الأقل)",
    "auth.loggingIn": "جاري تسجيل الدخول...",
    "auth.signingUp": "جاري إنشاء الحساب...",
    
    // Admin
    "admin.dashboard": "لوحة التحكم",
    "admin.users": "المستخدمون",
    "admin.academies": "الأكاديميات",
    "admin.matches": "المباريات",
    "admin.requests": "طلبات اللاعبين",
    "admin.createAcademy": "إنشاء حساب أكاديمية",
    "admin.panel": "لوحة الإدارة",
    "admin.usersManagement": "إدارة المستخدمين",
    "admin.administrators": "المديرون",
    "admin.academyAccounts": "حسابات الأكاديميات",
    "admin.regularUsers": "المستخدمون",
    "admin.addUser": "إضافة مستخدم",
    "admin.delete": "حذف",
    "admin.noAdmins": "لا يوجد مديرون",
    "admin.noAcademies": "لا توجد حسابات أكاديميات",
    "admin.noUsers": "لا يوجد مستخدمون عاديون",
    "admin.welcomeBack": "مرحباً بعودتك",
    "admin.platformOverview": "إليك نظرة عامة على المنصة",
    "admin.totalUsers": "إجمالي المستخدمين",
    "admin.totalAcademies": "الأكاديميات",
    "admin.totalMatches": "المباريات",
    "admin.pendingRequests": "الطلبات المعلقة",
    "admin.recentRequests": "الطلبات الأخيرة",
    "admin.viewAll": "عرض الكل",
    "admin.quickActions": "الإجراءات السريعة",
    "admin.manageAcademies": "إدارة الأكاديميات",
    "admin.manageAcademiesDesc": "عرض وإدارة جميع أكاديميات كرة القدم",
    "admin.manageMatches": "إدارة المباريات",
    "admin.manageMatchesDesc": "الإشراف على المباريات والأحداث المجدولة",
    "admin.manageRequests": "إدارة الطلبات",
    "admin.manageRequestsDesc": "معالجة طلبات الانضمام للأكاديميات",
    "admin.manageUsers": "إدارة المستخدمين",
    "admin.manageUsersDesc": "عرض وإدارة حسابات المستخدمين",
    "admin.platformStatus": "حالة المنصة",
    "admin.allSystemsOperational": "جميع الأنظمة تعمل بشكل طبيعي",
    "admin.online": "متصل",
    "admin.noRequestsYet": "لا توجد طلبات بعد",
    
    // Academy
    "academy.dashboard": "لوحة التحكم",
    "academy.players": "اللاعبون",
    "academy.matches": "المباريات",
    "academy.requests": "الطلبات",
    "academy.analysis": "التحليل",
    "academy.jobs": "الوظائف",
    "academy.panel": "لوحة الأكاديمية",
    "academy.welcomeBack": "مرحباً بعودتك",
    "academy.overview": "إليك نظرة عامة على أكاديميتك",
    "academy.totalPlayers": "إجمالي اللاعبين",
    "academy.activeMatches": "المباريات النشطة",
    "academy.pendingRequests": "الطلبات المعلقة",
    "academy.jobPostings": "عروض الوظائف",
    "academy.recentActivity": "النشاط الأخير",
    "academy.viewAll": "عرض الكل",
    "academy.quickActions": "الإجراءات السريعة",
    "academy.managePlayers": "إدارة اللاعبين",
    "academy.managePlayersDesc": "عرض وإدارة لاعبي الأكاديمية",
    "academy.scheduleMatch": "جدولة مباراة",
    "academy.scheduleMatchDesc": "إنشاء طلبات مباريات جديدة",
    "academy.viewRequests": "عرض الطلبات",
    "academy.viewRequestsDesc": "معالجة طلبات انضمام اللاعبين",
    "academy.postJob": "نشر وظيفة",
    "academy.postJobDesc": "إنشاء فرص عمل جديدة",
    "academy.academyStatus": "حالة الأكاديمية",
    "academy.allSystemsOperational": "جميع الأنظمة تعمل بشكل طبيعي",
    "academy.online": "متصل",
    "academy.noActivityYet": "لا يوجد نشاط بعد",
    "academy.totalPlayers": "إجمالي اللاعبين",
    "academy.avgAge": "متوسط العمر",
    "academy.positionBreakdown": "توزيع المراكز",
    "academy.quickActions": "الإجراءات السريعة",
    "academy.addPlayer": "إضافة لاعب",
    "academy.refresh": "تحديث",
    "academy.searchPlayers": "البحث عن اللاعبين...",
    "academy.filterAllPositions": "تصفية: جميع المراكز",
    "academy.clearFilter": "مسح التصفية",
    "academy.noDataYet": "لا توجد بيانات بعد",
    "academy.noPlayersFound": "لم يتم العثور على لاعبيين",
    "academy.addNewPlayer": "إضافة لاعب جديد",
    "academy.fullName": "الاسم الكامل",
    "academy.age": "العمر",
    "academy.position": "المركز",
    "academy.selectPosition": "اختر المركز (اختياري)",
    "academy.forward": "مهاجم",
    "academy.midfielder": "وسط",
    "academy.defender": "مدافع",
    "academy.goalkeeper": "حارس مرمى",
    "academy.other": "آخر",
    "academy.uploadAvatar": "رفع الصورة الشخصية (اختياري)",
    "academy.saving": "جاري الحفظ...",
    "academy.savePlayer": "حفظ اللاعب",
    "academy.deletePlayer": "حذف اللاعب",
    "academy.deletePlayerConfirm": "حذف اللاعب؟ لا يمكن التراجع عن هذا الإجراء.",
    "academy.couldNotRemovePlayer": "لا يمكن حذف اللاعب",
    "academy.pleaseProvideName": "يرجى تقديم اسم اللاعب",
    "academy.failedToAddPlayer": "فشل في إضافة اللاعب",
    
    // Common
    "common.loading": "جاري التحميل...",
    "common.error": "خطأ",
    "common.retry": "إعادة المحاولة",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.edit": "تعديل",
    "common.delete": "حذف",
    "common.confirm": "تأكيد",
    "common.yes": "نعم",
    "common.no": "لا",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.previous": "السابق",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.clear": "مسح",
    "common.submit": "إرسال",
    "common.close": "إغلاق",
    "common.open": "فتح",
    "common.view": "عرض",
    "common.details": "التفاصيل",
    "common.status": "الحالة",
    "common.date": "التاريخ",
    "common.time": "الوقت",
    "common.location": "الموقع",
    "common.description": "الوصف",
    "common.name": "الاسم",
    "common.email": "البريد الإلكتروني",
    "common.phone": "رقم الهاتف",
    "common.role": "الدور",
    "common.active": "نشط",
    "common.inactive": "غير نشط",
    "common.pending": "في الانتظار",
    "common.approved": "موافق عليه",
    "common.rejected": "مرفوض",
    "common.failed": "فشل",
    "common.success": "نجح",
    "common.warning": "تحذير",
    "common.info": "معلومات",
    "common.notFound": "غير موجود",
    "common.accessDenied": "الوصول مرفوض",
    "common.unauthorized": "غير مخول",
    "common.forbidden": "محظور",
    "common.serverError": "خطأ في الخادم",
    "common.networkError": "خطأ في الشبكة",
    "common.tryAgain": "حاول مرة أخرى",
    "common.refresh": "تحديث",
    "common.somethingWentWrong": "حدث خطأ ما",
    "common.pleaseRefresh": "يرجى تحديث الصفحة. إذا استمرت المشكلة، حاول مرة أخرى لاحقاً.",
    "common.failedToLoad": "فشل في تحميل",
    "common.confirmDelete": "هل أنت متأكد من حذف هذا",
    "common.user": "المستخدم",
    "common.failedToDelete": "فشل في حذف",
    
    // Public Pages
    "public.welcome": "مرحباً بك في دورلي",
    "public.tagline": "ربط عائلات كرة القدم المصرية بأفضل الأكاديميات",
    "public.getStarted": "ابدأ الآن",
    "public.learnMore": "اعرف المزيد",
    "public.features": "المميزات",
    "public.findAcademies": "البحث عن الأكاديميات",
    "public.findAcademiesDesc": "اكتشف أفضل أكاديميات كرة القدم في مصر",
    "public.scheduleMatches": "جدولة المباريات",
    "public.scheduleMatchesDesc": "تنظيم المباريات بين الأكاديميات",
    "public.jobOpportunities": "فرص العمل",
    "public.jobOpportunitiesDesc": "العثور على وظائف التدريب والتدريب",
    "public.playerManagement": "إدارة اللاعبين",
    "public.playerManagementDesc": "تتبع تقدم وتطوير اللاعبين",
    "public.aboutUs": "من نحن",
    "public.aboutUsDesc": "دورلي مكرس لدعم تطوير كرة القدم المصرية",
    "public.contact": "اتصل بنا",
    "public.followUs": "تابعنا",
    "public.madeForEgyptian": "صُنع لعائلات كرة القدم المصرية. ⚽🇪🇬",
    
    // Academies Page
    "academies.title": "الأكاديميات",
    "academies.search": "بحث",
    "academies.add": "إضافة",
    "academies.verified": "موثق",
    "academies.rating": "التقييم",
    "academies.location": "الموقع",
    "academies.phone": "الهاتف",
    "academies.email": "البريد الإلكتروني",
    "academies.subscription": "الاشتراك",
    "academies.girls": "البنات",
    "academies.boys": "الأولاد",
    "academies.training": "التدريب",
    "academies.join": "انضم",
    "academies.joining": "جاري الانضمام...",
    "academies.approved": "موافق عليه",
    "academies.rejected": "مرفوض (يمكن إعادة التقديم)",
    "academies.pending": "في الانتظار",
    "academies.close": "إغلاق",
    "academies.refresh": "تحديث",
    "academies.delete": "حذف",
    "academies.addAcademy": "إضافة أكاديمية",
    "academies.pickLocation": "اختر الموقع على الخريطة",
    "academies.initialRating": "التقييم الأولي",
    "academies.groups": "المجموعات",
    "academies.subscriptionPrice": "سعر الاشتراك (جنيه مصري)",
    "academies.trainingTimes": "أوقات التدريب",
    "academies.day": "اليوم",
    "academies.time": "الوقت",
    "academies.cancel": "إلغاء",
    "academies.save": "حفظ",
    "academies.joinRequestSent": "تم إرسال طلب الانضمام بنجاح!",
    "academies.joinRequestFailed": "فشل في إرسال طلب الانضمام.",
    
    // Job Opportunities Page
    "jobs.title": "فرص العمل التدريبية",
    "jobs.subtitle": "اعثر على وظيفتك التدريبية التالية في أفضل أكاديميات كرة القدم في مصر. قدم بملفك الشخصي وابدأ رحلتك التدريبية.",
    "jobs.search": "البحث عن الوظائف أو الأكاديميات أو المواقع...",
    "jobs.filter": "تصفية",
    "jobs.allTypes": "جميع الأنواع",
    "jobs.fullTime": "دوام كامل",
    "jobs.partTime": "دوام جزئي",
    "jobs.contract": "عقد",
    "jobs.volunteer": "متطوع",
    "jobs.availableJobs": "الوظائف المتاحة",
    "jobs.participatingAcademies": "الأكاديميات المشاركة",
    "jobs.yourApplications": "طلباتك",
    "jobs.noJobsFound": "لم يتم العثور على وظائف",
    "jobs.tryAdjusting": "حاول تعديل معايير البحث أو التصفية",
    "jobs.checkBackLater": "تحقق مرة أخرى لاحقاً للحصول على فرص جديدة",
    "jobs.loading": "جاري تحميل فرص العمل...",
    "jobs.applyNow": "قدم الآن",
    "jobs.youHaveApplied": "لقد تقدمت لهذه الوظيفة",
    "jobs.rejectedCanReapply": "مرفوض (يمكن إعادة التقديم)",
    "jobs.deadlinePassed": "انتهت مهلة التقديم",
    "jobs.deadlinePassedTitle": "انتهت المهلة",
    "jobs.applyForPosition": "التقديم للوظيفة",
    "jobs.coverLetter": "خطاب التغطية",
    "jobs.coverLetterPlaceholder": "أخبرنا لماذا أنت الأنسب لهذه الوظيفة...",
    "jobs.coachingExperience": "خبرة التدريب",
    "jobs.experiencePlaceholder": "اوصف خبرتك التدريبية وإنجازاتك...",
    "jobs.qualifications": "المؤهلات والشهادات",
    "jobs.qualificationsPlaceholder": "اذكر رخص التدريب والشهادات والمؤهلات ذات الصلة...",
    "jobs.uploadCV": "رفع السيرة الذاتية",
    "jobs.clickToUpload": "انقر لرفع سيرتك الذاتية",
    "jobs.cvFormats": "PDF أو DOC أو DOCX (حد أقصى 5 ميجابايت)",
    "jobs.cvUploaded": "تم رفع السيرة الذاتية بنجاح",
    "jobs.submitApplication": "إرسال الطلب",
    "jobs.submitting": "جاري الإرسال...",
    "jobs.pleaseWriteCoverLetter": "يرجى كتابة خطاب تغطية",
    "jobs.pleaseUploadCV": "يرجى رفع سيرتك الذاتية",
    "jobs.cvFileSizeLimit": "يجب أن يكون حجم ملف السيرة الذاتية أقل من 5 ميجابايت",
    "jobs.applicationSubmitted": "تم إرسال الطلب بنجاح!",
    "jobs.failedToSubmit": "فشل في إرسال الطلب",
    "jobs.requirements": "المتطلبات:",
    "jobs.posted": "نُشر",
    "jobs.applyBy": "قدم قبل",
    "jobs.at": "في",
    "jobs.availableJobs": "الوظائف المتاحة",
    "jobs.participatingAcademies": "الأكاديميات المشاركة",
    "jobs.yourApplications": "طلباتك",
    "jobs.requirements": "المتطلبات:",
    "jobs.applyNow": "قدم الآن",
    "jobs.rating": "التقييم",
    "jobs.subscription": "الاشتراك",
    "jobs.groups": "المجموعات",
    "jobs.girls": "البنات",
    "jobs.boys": "الأولاد",
    "jobs.contact": "اتصل بنا",
    "jobs.location": "الموقع",
    "jobs.trainingTimes": "أوقات التدريب",
    "jobs.uploadAvatarsFilter": "رفع الصور الشخصية، تصفية وتحليل.",
    "jobs.defender": "مدافع",
    "jobs.midfielder": "وسط",
    "jobs.forward": "مهاجم",
    "jobs.age": "العمر",
    
    // Academy Match Requests
    "academyMatch.title": "طلبات مباريات الأكاديمية",
    "academyMatch.description": "إدارة طلبات المباريات والعثور على خصوم",
    "academyMatch.newRequest": "طلب جديد",
    "academyMatch.available": "متاح",
    "academyMatch.confirmed": "مؤكد",
    "academyMatch.finished": "منتهي",
    "academyMatch.matchDateTime": "تاريخ ووقت المباراة",
    "academyMatch.ageGroup": "الفئة العمرية",
    "academyMatch.contactDuration": "التواصل والمدة",
    "academyMatch.finishMatch": "إنهاء المباراة",
    "academyMatch.hour": "ساعة",
    
    // Academy Requests
    "academyRequests.title": "طلبات الانضمام",
    "academyRequests.noRequests": "لا توجد طلبات انضمام بعد.",
    
    // Academy Analytics
    "academyAnalytics.title": "تحليلات الأكاديمية",
    "academyAnalytics.description": "مؤشرات الأداء الرئيسية المباشرة للاعبين والمباريات والطلبات والمالية.",
    "academyAnalytics.refresh": "تحديث",
    "academyAnalytics.players": "اللاعبون",
    "academyAnalytics.matches": "المباريات",
    "academyAnalytics.income": "الدخل",
    "academyAnalytics.balance": "الرصيد",
    "academyAnalytics.playersByPosition": "اللاعبون حسب المركز",
    "academyAnalytics.playersByAge": "اللاعبون حسب العمر",
    "academyAnalytics.matchesRequests": "المباريات والطلبات",
    "academyAnalytics.matchesStatus": "حالة المباريات",
    "academyAnalytics.playerRequests": "طلبات اللاعبين",
    "academyAnalytics.noRequestsYet": "لا توجد طلبات بعد.",
    "academyAnalytics.total": "المجموع",
    
    // Finance
    "finance.title": "المالية",
    "finance.income": "الدخل",
    "finance.amount": "المبلغ (جنيه مصري)",
    "finance.category": "الفئة",
    "finance.date": "الشهر/اليوم/السنة",
    "finance.note": "ملاحظة",
    "finance.addEntry": "إضافة إدخال",
    "finance.incomeType": "دخل",
    
    // Admin
    "admin.addAcademy": "إضافة أكاديمية",
    "admin.createAcademyAccount": "إنشاء حساب أكاديمية",
    "admin.selectAcademy": "اختر الأكاديمية",
    "admin.chooseAcademy": "اختر أكاديمية...",
    "admin.email": "البريد الإلكتروني",
    "admin.password": "كلمة المرور",
    "admin.createAccount": "إنشاء حساب",
    "admin.friendlyMatches": "مباريات ودية",
    "admin.playerRequests": "طلبات اللاعبين",
    "admin.noPlayerRequests": "لم يتم العثور على طلبات لاعبيين",
    
    // Language
    "lang.english": "English",
    "lang.arabic": "العربية",
    "lang.switchTo": "التبديل إلى",
    
    // Home Page
    "home.verified": "موثق",
    "home.verifiedDesc": "نظام التحقق المدعوم بالذكاء الاصطناعي",
    "home.rated": "مقيم",
    "home.ratedDesc": "تقييمات مدفوعة من المجتمع",
    "home.connected": "متصل",
    "home.connectedDesc": "مطابقة سلسة",
    "home.verifiedProfiles": "الملفات الشخصية الموثقة",
    "home.verifiedProfilesDesc": "جميع الأكاديميات موثقة ومقيمة من قبل مجتمعنا",
    "home.performanceTracking": "تتبع الأداء",
    "home.performanceTrackingDesc": "مراقبة أداء الأكاديمية وتطوير اللاعبين",
    "home.communityRatings": "تقييمات المجتمع",
    "home.communityRatingsDesc": "مراجعات وتقييمات حقيقية من اللاعبين وأولياء الأمور",
    "home.elevatingEgyptian": "رفع مستوى المواهب المصرية لكرة القدم",
    
    // Matches Page
    "matches.title": "المباريات الودية",
    "matches.search": "البحث بالتاريخ أو الحالة أو الفئة العمرية...",
    "matches.matched": "مطابق",
    "matches.requested": "مطلوب",
    "matches.accepted": "مقبول",
    "matches.scheduled": "مجدول",
    "matches.contact": "التواصل:",
    "matches.acceptAndShow": "قبول وإظهار جهات الاتصال",
    "matches.requestMatch": "طلب مباراة ودية",
    "matches.ageGroup": "الفئة العمرية",
    "matches.date": "التاريخ",
    "matches.time": "الوقت",
    "matches.homeAway": "داخل / خارج",
    "matches.home": "داخل",
    "matches.away": "خارج",
    "matches.location": "الموقع",
    "matches.publishing": "جاري النشر...",
    "matches.publish": "نشر",
    "matches.onlyAcademyAccounts": "يمكن لحسابات الأكاديميات فقط نشر طلبات المباريات. يرجى الاتصال بالإدارة لموافقة الوصول للأكاديمية.",
    "matches.chooseDateTime": "يرجى اختيار التاريخ والوقت",
    "matches.pickLocation": "يرجى اختيار موقع على الخريطة",
    "matches.failedToPublish": "فشل في النشر",
    "matches.failedToAccept": "فشل في القبول",
    
    // Admin Academies
    "adminAcademies.title": "الإدارة • الأكاديميات",
    "adminAcademies.addAcademy": "إضافة أكاديمية",
    "adminAcademies.retry": "إعادة المحاولة",
    "adminAcademies.edit": "تعديل",
    "adminAcademies.delete": "حذف",
    "adminAcademies.prev": "السابق",
    "adminAcademies.next": "التالي",
    "adminAcademies.page": "صفحة",
    "adminAcademies.of": "من",
    "adminAcademies.addAcademyModal": "إضافة أكاديمية",
    "adminAcademies.editAcademyModal": "تعديل الأكاديمية",
    "adminAcademies.nameEnglish": "الاسم (بالإنجليزية)*",
    "adminAcademies.nameArabic": "الاسم (بالعربية)",
    "adminAcademies.academyName": "اسم الأكاديمية",
    "adminAcademies.academyNameAr": "اسم الأكاديمية",
    "adminAcademies.phone": "الهاتف",
    "adminAcademies.phoneNumber": "رقم الهاتف",
    "adminAcademies.contactEmail": "البريد الإلكتروني للتواصل",
    "adminAcademies.description": "الوصف",
    "adminAcademies.academyDescription": "وصف الأكاديمية",
    "adminAcademies.locationDescription": "وصف الموقع",
    "adminAcademies.location": "الموقع",
    "adminAcademies.rating": "التقييم:",
    "adminAcademies.availableAges": "الأعمار المتاحة",
    "adminAcademies.verified": "موثق",
    "adminAcademies.girls": "البنات",
    "adminAcademies.boys": "الأولاد",
    "adminAcademies.subscriptionPrice": "سعر الاشتراك (جنيه مصري)",
    "adminAcademies.trainingTimes": "أوقات التدريب",
    "adminAcademies.addTime": "إضافة وقت",
    "adminAcademies.day": "اليوم",
    "adminAcademies.time": "الوقت",
    "adminAcademies.logoImage": "الشعار / الصورة",
    "adminAcademies.preview": "معاينة",
    "adminAcademies.currentLogo": "الشعار الحالي",
    "adminAcademies.selected": "المحدد:",
    "adminAcademies.cancel": "إلغاء",
    "adminAcademies.creating": "جاري الإنشاء...",
    "adminAcademies.create": "إنشاء",
    "adminAcademies.saving": "جاري الحفظ...",
    "adminAcademies.save": "حفظ",
    "adminAcademies.nameRequired": "الاسم مطلوب لإنشاء أكاديمية.",
    "adminAcademies.failedToCreate": "فشل في إنشاء الأكاديمية.",
    "adminAcademies.failedToUpdate": "فشل في تحديث الأكاديمية.",
    "adminAcademies.confirmDelete": "هل أنت متأكد من حذف هذه الأكاديمية؟",
    "adminAcademies.failedToDelete": "فشل في حذف الأكاديمية.",
    "adminAcademies.failedToLoad": "فشل في تحميل الأكاديميات. يرجى المحاولة مرة أخرى.",
    
    // Academies Page
    
    // Academy Dashboard
    "academy.configurationRequired": "التكوين مطلوب",
    "academy.academyInfoMissing": "معلومات الأكاديمية مفقودة. يرجى الاتصال بالإدارة لربط حسابك بأكاديمية.",
    "academy.contactAdminToResolve": "لحل هذه المشكلة، يرجى الاتصال بالإدارة لربط حساب الأكاديمية بشكل صحيح بأكاديمية.",
    "academy.totalRequests": "إجمالي الطلبات",
  }
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Get from localStorage or default to English
    return localStorage.getItem('dwarly-language') || 'en'
  })

  useEffect(() => {
    // Save to localStorage when language changes
    localStorage.setItem('dwarly-language', language)
    
    // Update document direction and lang attribute
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'
    document.documentElement.lang = language
  }, [language])

  const t = (key) => {
    return translations[language]?.[key] || key
  }

  const switchLanguage = (newLang) => {
    setLanguage(newLang)
  }

  return (
    <LanguageContext.Provider value={{ language, t, switchLanguage }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
